<?xml version="1.0"?>
<robot name="smartcar" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Properties for the robot -->
  <xacro:property name="wheel_diameter" value="0.064"/>
  <xacro:property name="wheel_width" value="0.025"/>
  <xacro:property name="wheelbase_length" value="0.257"/>
  <xacro:property name="wheelbase_width" value="0.17"/>

  <material name="blue">
    <color rgba="0 0 1 1"/>
  </material>

  <material name="red">
    <color rgba="1 0 0 1"/>
  </material>

  <material name="green">
    <color rgba="0 1 0 1"/>
  </material>

  <material name="black">
    <color rgba="0 0 0 1"/>
  </material>

<!-- Robot base -->
<link name="base_link">
    <visual>
        <origin xyz="0 0 0.02"/>  <!-- Adjust height to lower base link -->
        <geometry>
            <box size="${wheelbase_length} ${wheelbase_width} 0.03" />
        </geometry>
        <material name="blue" />
    </visual>
    <collision>
        <origin xyz="0 0 0.01"/>  <!-- Match visual height -->
        <geometry>
            <box size="${wheelbase_length} ${wheelbase_width} 0.03" />
        </geometry>
    </collision>
    <inertial>
        <mass value="5.0"/>
        <origin xyz="0 0 0.01"/>  <!-- Match height -->
        <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.03"/>
    </inertial>
</link>


<!-- Chassis -->
<link name="chassis_link">
    <visual>
        <origin xyz="0 0 0.01"/>  <!-- Position higher than the base link -->
        <geometry>
            <box size="${wheelbase_length} ${wheelbase_width} 0.03" />
        </geometry>
        <material name="red"/>
    </visual>
    <collision>
        <origin xyz="0 0 0.01"/>  <!-- Match visual height -->
        <geometry>
            <box size="${wheelbase_length} ${wheelbase_width} 0.03" />
        </geometry>
    </collision> 
    <inertial>
        <mass value="2.0"/>
        <origin xyz="0 0 0.01"/>  <!-- Match height -->
        <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.03"/>
    </inertial>
</link>

<!-- Fixed joint between base_link and chassis_link -->
<joint name="chassis_joint" type="fixed">
    <parent link="base_link"/>
    <child link="chassis_link"/>
    <origin xyz="0 0 0.03"/>  <!-- Ensure the chassis sits on top of the base link -->
</joint>

  <!-- Wheels -->
  <xacro:macro name="wheel" params="name joint_parent joint_name xyz_offset">
    <link name="${name}">
      <visual>
        <geometry>
          <cylinder radius="${wheel_diameter / 2}" length="${wheel_width}" />
        </geometry>
        <material name="black" />
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${wheel_diameter / 2}" length="${wheel_width}" />
        </geometry>
      </collision>
      <inertial>
        <mass value="0.1"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
      </inertial>
    </link>

    <joint name="${joint_name}" type="continuous">
      <parent link="${joint_parent}"/>
      <child link="${name}"/>
      <origin xyz="${xyz_offset} ${wheel_diameter / 2}" rpy="1.57 0 0"/>
      <axis xyz="0 0 1"/>
    </joint>
  </xacro:macro>

  <!-- Rear wheels (fixed position) -->
  <xacro:wheel name="back_left_wheel" joint_parent="base_link" joint_name="back_left_wheel_joint" xyz_offset="-${wheelbase_length / 2} -${wheelbase_width / 2}"/>
  <xacro:wheel name="back_right_wheel" joint_parent="base_link" joint_name="back_right_wheel_joint" xyz_offset="-${wheelbase_length / 2} ${wheelbase_width / 2}"/>

  <!-- Front wheels with steering links -->
  <link name="front_left_steering_link">
    <inertial>
        <mass value="0.1"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
    </inertial>
  </link>
  <link name="front_right_steering_link">
    <inertial>
        <mass value="0.1"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
    </inertial>
  </link>

  <!-- Front wheels with steering enabled -->
  <joint name="front_left_steer_joint" type="revolute">
    <parent link="base_link"/>
    <child link="front_left_steering_link"/>
    <origin xyz="${wheelbase_length / 2} -${wheelbase_width / 2} 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-${45*(3.1415 /180)}" upper="${45*(3.1415 /180)}" effort="10" velocity="1"/>
  </joint>
  <joint name="front_right_steer_joint" type="revolute">
    <parent link="base_link"/>
    <child link="front_right_steering_link"/>
    <origin xyz="${wheelbase_length / 2} ${wheelbase_width / 2} 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-${45*(3.1415 /180)}" upper="${45*(3.1415 /180)}" effort="10" velocity="1"/>
  </joint>

  <!-- Front wheels attached to steering links -->
  <xacro:wheel name="front_left_wheel" joint_parent="front_left_steering_link" joint_name="front_left_wheel_joint" xyz_offset="0 0"/>
  <xacro:wheel name="front_right_wheel" joint_parent="front_right_steering_link" joint_name="front_right_wheel_joint" xyz_offset="0 0"/>

  
  <!-- Define parent_link as a property -->
<xacro:property name="parent_link" value="chassis_link"/>

<!--imu_sensor-->
  <link name="imu_link">
    <inertial>
      <origin xyz="0 0 0" />
      <mass value="0.1" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
    </inertial>
  </link>

  <joint name="imu_joint" type="fixed">
    <parent link="${parent_link}" />
    <child link="imu_link" />
    <origin xyz="0 0 0.3" rpy="0 0 0" />
  </joint>

  <gazebo>
    <plugin name="imu_plugin" filename="gazebo_ros_imu_sensor">
      <ros>
        <namespace>/</namespace>
        <remapping>imu_data:=/imu_data</remapping>
      </ros>
      <link_name>imu_link</link_name>
    </plugin>
  </gazebo>


<!--lidar_sensor-->
  <link name="sllidar_base_link">
    <inertial>
      <origin xyz="0 0 0.3" />
      <mass value="0.2" />
      <inertia ixx="0.002" ixy="0.0" ixz="0.0" iyy="0.002" iyz="0.0" izz="0.002" />
    </inertial>
  </link>

  <joint name="lidar_joint" type="fixed">
    <parent link="${parent_link}" />
    <child link="sllidar_base_link" />
    <origin xyz="1.0 0 0.3" rpy="0 0 0" />
  </joint>

  <gazebo>
    <plugin name="lidar_plugin" filename="gazebo_ros_ray_sensor">
      <ros>
        <namespace>/</namespace>
        <remapping>scan:=/scan</remapping>
      </ros>
      <topicName>/scan</topicName>
      <linkName>sllidar_base_link</linkName>
      <minAngle>-1.5708</minAngle>
      <maxAngle>1.5708</maxAngle>
      <updateRate>10.0</updateRate>
    </plugin>
  </gazebo>

</robot>